language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '9'
install:
- npm install -g greenkeeper-lockfile@1
- npm install
before_script: greenkeeper-lockfile-update
script:
- npm test
- npm run build
- npm run bundle
after_script: greenkeeper-lockfile-upload
after_success:
- npm run coverage
- npm run semantic-release
before_deploy:
- git checkout package.json
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"