language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '9'
install:
- yarn global add greenkeeper-lockfile@1
- yarn install
before_script: greenkeeper-lockfile-update
script:
- yarn test
- yarn run build
- yarn run bundle
after_script: greenkeeper-lockfile-upload
after_success:
- yarn run coverage
- yarn run semantic-release
before_deploy:
- git checkout package.json
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"